name: "Terraform Test"

on:
  push:
    branches:
      - "main"

env:
  AMR_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AMR_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AMR_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AMR_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:

  terraform-test:

    name: "Terraform Test"
    runs-on: ubuntu-latest

    steps:

      # Checkout the repository to the GitHub Action Runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest verssion of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize terraform 
      - name: Terraform Init
        run: az login -u ${{ secrets.AZ_USERNAME }} -p ${{ secrets.AZ_PASSWORD }} && terraform init

      # Format the file
      - name: Terraform Format
        run: terraform fmt -check

      # Validate terraform file
      - name: Terraform Validate
        run: terraform validate